version: '3.9'

services:
  postgres:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=debt_management_all
      - POSTGRES_USER=admin_all
      - POSTGRES_PASSWORD=admin_all
    volumes:
      - ./create_application_user.sql:/docker-entrypoint-initdb.d/create_application_user.sql
